[package]
name = "ezsockets-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
ezsockets = { version = "0.6.2", features = ["tungstenite"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.20"
